- name: Add nginx repo
  copy:
    src: nginx_repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: '0644'

- name: Update yum cache and install nginx
  yum:
    name: nginx
    state: latest
    update_cache: yes

- name: Enable nginx autostart
  service:
    name: nginx
    enabled: yes

- name: Install nginx config
  template:
    src: nginx_conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart nginx

- name: Test nginx
  shell: "nginx -t"
